version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ../logs:/app/logs
      - ../outputs:/app/outputs
      - ../static:/app/static
      - ../cours:/app/cours
      - type: bind
        source: ${DB_PATH}
        target: /app/data/production.db
        consistency: delegated
    env_file:
      - ../.env
    environment:
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DB_PATH=/app/data/production.db
      - COURS_DIR=${COURS_DIR}
    restart: unless-stopped 